### ISSUE TITLE
For milliseconds as third digit always remains 0, please keep only two digits like seconds, minutes and hours

### ISSUE THREAD

**Issue by NumanNaseerNomi** [iLaibaHabib/Stopwatch#4]
![image](https://github.com/iLaibaHabib/Stopwatch/assets/61705661/d874b95a-c200-451e-81aa-dd7119c7f78d)
![image](https://github.com/iLaibaHabib/Stopwatch/assets/61705661/fe1e17d6-ca28-45e2-b191-cee7b0581dff)

**Comment by iLaibaHabib** [comment]
@iLaibaHabib  both branches are not fixing the issue

working-millisecond-third-digit
change-millisecond-digits-

**Comment by NumanNaseerNomi** [comment]
@iLaibaHabib please apply these changes to fix this issue

![image](https://github.com/iLaibaHabib/Stopwatch/assets/61705661/9a327141-8ebf-4b18-a4ab-48c6eedfaafe)
